services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
      network: host
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/home/node/app/
      - ./web/node_modules:/home/node/app/node_modules/

  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: price
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
      
  fetching-service:
    build: 
      context: ./data-fetching-service
      network: host
    ports:
      - 5001:5000
    depends_on:
      - database
    volumes:
      - ./data-fetching-service:/usr/src/app
    entrypoint: python app.py